# Generated by Django 3.2.25 on 2025-08-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='seed',
        ),
    ]
