# Generated by Django 3.2.25 on 2025-08-27 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('focus_area', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('intensity', models.IntegerField(help_text='Rate intensity from 1 (low) to 10 (high)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='profiles.playerprofile')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
