# Generated by Django 3.2.25 on 2025-08-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('surface_type', models.CharField(choices=[('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard', 'Hard'), ('Carpet', 'Carpet')], default='Hard', max_length=50)),
                ('indoor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.tenniscourt'),
        ),
    ]
