# Generated by Django 3.2.25 on 2025-08-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('training', '0002_auto_20250828_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='player',
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='scheduled', max_length=10),
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=10)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.playerprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingsession')),
            ],
            options={
                'unique_together': {('session', 'player')},
            },
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='players',
            field=models.ManyToManyField(related_name='training_sessions', through='training.SessionParticipant', to='profiles.PlayerProfile'),
        ),
    ]
