# Generated by Django 3.2.25 on 2025-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20250828_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
