# Generated by Django 3.2.25 on 2025-08-28 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_trainingsession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='intended_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('competition', 'Competition')], default='intermediate', help_text='Intended skill level for this session', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='max_players',
            field=models.IntegerField(default=4, help_text='Maximum 4 players allowed per session', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
